name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    env:
       PERL_USE_UNSAFE_INC: 0
       AUTHOR_TESTING: 1
       AUTOMATED_TESTING: 1
       RELEASE_TESTING: 1
       PERL_CARTON_PATH: $GITHUB_WORKSPACE/local
       LD_LIBRARY_PATH: /usr/local/lib

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - latest

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install cmake
        run: apt --assume-yes install cmake
      - name: Download & install LWS
        run: |
            git clone https://libwebsockets.org/repo/libwebsockets
            cd libwebsockets
            mkdir build
            cd build
            cmake -DCMAKE_INSTALL_PREFIX=`pwd` ..
            cd ../..
      - name: Install AnyEvent (optional)
        run: "cpanm --notest AnyEvent ||:"
      - name: Install IO::Async (optional)
        run: "cpanm --notest IO::Async ||:"
      - name: Install Mojolicious (optional)
        run: "cpanm --notest Mojolicious ||:"
      - name: Install Configure Requires
        run: cpanm ExtUtils::CChecker ExtUtils::PkgConfig
      - name: Install Dependencies
        run: cpanm --notest --installdeps .
      - name: perl Makefile.PL
        run: LWS_BUILD_DIR=../libwebsockets/build perl Makefile.PL
      - name: make
        run: make
      - name: Run Tests
        run: make test
