name: linux-custom-lws

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    env:
       PERL_USE_UNSAFE_INC: 0
       AUTHOR_TESTING: 1
       AUTOMATED_TESTING: 1
       RELEASE_TESTING: 1
       PERL_CARTON_PATH: $GITHUB_WORKSPACE/local
       LD_LIBRARY_PATH: /usr/local/lib

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - latest

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - name: perl -V
        run: perl -V
      - name: Install cmake
        run: apt --assume-yes install cmake
      - name: Download & install LWS
        run: |
            git clone https://libwebsockets.org/repo/libwebsockets
            cd libwebsockets
            mkdir build
            cd build
            cmake -DCMAKE_INSTALL_PREFIX=../../../my-lws -DLWS_WITHOUT_EXTENSIONS=0 -DLWS_WITH_SYS_ASYNC_DNS=1 ..
            make install
            cd ../..
            rm -rf libwebsockets
      - name: Install Dependencies
        run: cpanm --verbose --notest --installdeps --with-configure .
      #- run: find /github/home/.cpanm/work -name build.log
      #- run: "for f in `find /github/home/.cpanm/work -name build.log`; do echo ========== $f; cat $f; done"
      - run: pwd
      - name: perl Makefile.PL
        run: LWS_BUILD_DIR=../my-lws perl Makefile.PL
      - name: make
        run: make
      - name: Test PMD support
        run: "perl -Mblib -MTest::More -MNet::Libwebsockets -e'is Net::Libwebsockets::HAS_PMD(), 1, q<per-message deflate support>; done_testing'"
