name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: macOS-latest

    env:
       PERL_USE_UNSAFE_INC: 0
       AUTHOR_TESTING: 1
       AUTOMATED_TESTING: 1
       RELEASE_TESTING: 1
       PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Set up LWS
        run: brew install libwebsockets
      - name: Link Homebrew OpenSSL
        run: ln -s /usr/local/Cellar/openssl@1.1/include/openssl /usr/local/include
      - name: Saving PKG_CONFIG_PATH in a file
        run: find /usr/local/Cellar/openssl@1.1 -name pkgconfig > .pkg-config-path
      - name: Saving PERL_MM_OPT in a file
        run: "export PKG_CONFIG_PATH=`cat .pkg-config-path`; echo CCFLAGS=\\'`pkg-config openssl --cflags`\\' LIBS=\\'`pkg-config openssl --libs`\\' > .perl_mm_opt"
      - name: Install Dependencies
        run: export PERL_MM_OPT="`cat .perl_mm_opt`"; export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"; export CFLAGS="-I/usr/local/opt/openssl@1.1/include"; curl -L https://cpanmin.us | perl - --notest --installdeps --with-configure --with-develop .
      - name: perl Makefile.PL
        run: export PERL_MM_OPT="`cat .perl_mm_opt`"; export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"; export CFLAGS="-I/usr/local/opt/openssl@1.1/include"; export NLWS_IS_MACOS_CI=1; perl Makefile.PL
      - name: make
        run: make
      - name: Run tests (with coverage)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L https://cpanmin.us | perl - --notest Devel::Cover::Report::Coveralls
          `perl -MConfig -E'print $Config::Config{"sitebin"}'`/cover -test -report Coveralls
