name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: macOS-latest

    env:
       PERL_USE_UNSAFE_INC: 0
       AUTHOR_TESTING: 1
       AUTOMATED_TESTING: 1
       RELEASE_TESTING: 1
       PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    steps:
      - uses: actions/checkout@v2
      - name: Set up Perl & LWS
        run: brew install perl libwebsockets
      - run: which pkg-config
      - run: PKG_CONFIG_PATH=`find /usr/local/Cellar/openssl@1.1 -name pkgconfig` pkg-config --list-all | sort
      - run: export FOO=bar
      - run: "echo $FOO"
      - name: perl -V
        run: perl -V
      - name: Install AnyEvent (optional)
        run: "curl -L https://cpanmin.us | perl - --notest AnyEvent ||:"
      - name: Install IO::Async (optional)
        run: "curl -L https://cpanmin.us | perl - --notest IO::Async ||:"
      - name: Install Mojolicious (optional)
        run: "curl -L https://cpanmin.us | perl - --notest Mojolicious ||:"
      - name: Install Configure Requires
        run: curl -L https://cpanmin.us | perl - --notest ExtUtils::CChecker ExtUtils::PkgConfig
      - run: find /usr/local/Cellar/openssl@1.1 -name pkgconfig
      - name: Install Dependencies
        run: curl -L https://cpanmin.us | PKG_CONFIG_PATH=`find /usr/local/Cellar/openssl@1.1 -name pkgconfig` perl - --notest --installdeps . || cat `find ~ -name build.log`
      - name: perl Makefile.PL
        run: PKG_CONFIG_PATH=`find /usr/local/Cellar/openssl@1.1 -name pkgconfig` perl Makefile.PL
      - name: make
        run: make
      - name: Run tests (with coverage)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L https://cpanmin.us | perl - --notest Devel::Cover::Report::Coveralls
          `perl -MConfig -E'print $Config::Config{"sitebin"}'`/cover -test -report Coveralls
